-- Create trending table to cache trending movies and shows
CREATE TABLE IF NOT EXISTS "public"."trending" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "movie_db_id" bigint NOT NULL,
    "title" character varying NOT NULL,
    "poster_path" character varying,
    "release_date" character varying,
    "medium" text NOT NULL,
    "time_window" text NOT NULL,
    "trending_rank" smallint NOT NULL,
    "synced_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."trending" OWNER TO "postgres";

-- Add primary key
ALTER TABLE ONLY "public"."trending"
    ADD CONSTRAINT "trending_pkey" PRIMARY KEY ("id");

-- Add unique constraint to prevent duplicates for the same time window
ALTER TABLE ONLY "public"."trending"
    ADD CONSTRAINT "trending_unique_entry" UNIQUE ("movie_db_id", "medium", "time_window");

-- Add check constraints
ALTER TABLE ONLY "public"."trending"
    ADD CONSTRAINT "trending_medium_check" CHECK (medium IN ('movie', 'tv'));

ALTER TABLE ONLY "public"."trending"
    ADD CONSTRAINT "trending_time_window_check" CHECK (time_window IN ('day', 'week'));

-- Enable RLS
ALTER TABLE "public"."trending" ENABLE ROW LEVEL SECURITY;

-- Create policy for read access
CREATE POLICY "Enable read access for all users" ON "public"."trending" FOR SELECT USING (true);

-- Grant permissions
GRANT ALL ON TABLE "public"."trending" TO "anon";
GRANT ALL ON TABLE "public"."trending" TO "authenticated";
GRANT ALL ON TABLE "public"."trending" TO "service_role";

GRANT ALL ON SEQUENCE "public"."trending_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trending_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trending_id_seq" TO "service_role";

-- Create index for faster queries
CREATE INDEX "trending_medium_time_window_idx" ON "public"."trending" USING btree ("medium", "time_window", "trending_rank");
CREATE INDEX "trending_synced_at_idx" ON "public"."trending" USING btree ("synced_at" DESC);
